const danhSachPhimHan = [
    {   
        id:"tide-of-love",
        tieuDe: "Tide of Love",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Tide-of-Love.jpg",
        phuDe: "Tide of Love",

        thoiLuong:"100 phút",
        daoDien:"Unknown",
        dienVien:"Kim Hyeon Seo, Jung Myeong Cheol",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện về bên bờ biển, một bản hợp đồng ràng buộc hai người xa lạ: Han Jae Hun, một người thừa kế lạnh lùng che giấu nỗi đau, và Kim Hae Jun, một sinh viên mỹ thuật thông minh mang gánh nặng cuộc sống. Những gì bắt đầu như một giao dịch dần trở nên dịu dàng. Qua nỗi cô đơn ẩn giấu và sự quan tâm thầm lặng, họ dần trở nên gần gũi—nhưng bản hợp đồng vẫn giữ chặt trái tim họ. Khi thủy triều dâng cao và bí mật lộ diện, họ phải lựa chọn: tiếp tục bị ràng buộc bởi luật lệ, hay dám yêu một cách tự do. Một mùa thu, một căn biệt thự, một câu chuyện về sự gần gũi gượng ép và cảm xúc chân thật, chờ đợi thủy triều lên tiếng.",
    },
    {   
        id:"the-manipulated",
        tieuDe: "The Manipulated",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/The-Manipulated.jpg",
        phuDe:"The Manipulated",

        thoiLuong:"100 phút",
        daoDien:"Park Shin Woo, Kim Chang Ju",
        dienVien:"Ji Chang Wook, Doh Kyung Soo",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện xoay quanh Tae Jung do Ji Chang Wook thủ vai một người đàn ông bình thường bị buộc tội oan trong vụ án giết người được dàn dựng một cách tỉ mỉ và phải vào tù. Sau khi phát hiện ra mọi chuyện đều do Yohan do Do Kyung Soo thủ vai dàn dựng, anh quyết tâm trả thù."
    },
    {   
        id:"dear-x",
        tieuDe: "Dear X",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Dear-X.jpg",
        phuDe:"Dear X",

        thoiLuong:"100 phút",
        daoDien:"Lee Eung Bok, Park So Hyun",
        dienVien:"Kim You Jung, Kim Young Dae, Kim Do Hoon",
        khoiChieu:"01/01/2026",
        moTa:"Baek A Jin lớn lên trong cảnh bạo lực gia đình, buộc cô phải che giấu cảm xúc và sống sót bằng cách đọc vị và thao túng người khác. Bề ngoài, cô tỏ ra hào phóng và tốt bụng, nhưng khi tham vọng bị đe dọa, bản chất đen tối trong cô lại trỗi dậy. Với nhan sắc và tài năng, cô vươn lên trở thành một nữ diễn viên hàng đầu. Bên cạnh cô là Yun Jun Seo, người bạn tâm giao suốt đời và là người duy nhất cô tin tưởng. Vậy mà người đàn ông từng ủng hộ cô lại chính là người khiến cô sụp đổ. Cũng liên quan đến quá khứ của cô là Kim Jae O, người có quá khứ bị bạo hành và tìm thấy ở A Jin lý do để sống. Trong khi đó, nữ diễn viên đối thủ và cựu thần tượng Im Re Na lại nảy sinh tình cảm với Jun Seo, khiến cuộc sống của họ thêm phần căng thẳng.",
    },
    {   
        id:"peach-trap",
        tieuDe: "Peach Trap",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Phim-Peach-Trap.jpg",
        phuDe: "Peach Trap",

        thoiLuong:"100 phút",
        daoDien:"Kim Ah Young",
        dienVien:"Jung Su Bin, Cha Se Jin",
        khoiChieu:"01/01/2026",
        moTa:"Đúng lúc Yoo Do Ha đang trong cơn khủng hoảng lớn nhất cuộc đời, ba người đàn ông xuất hiện! Anh bị cuốn vào cơn bão tín hiệu tình yêu với cả ba người đàn ông. Thậm chí là cùng một lúc! Một cơn lốc số phận xoay quanh Do Ha. Cây gậy tình yêu cuối cùng sẽ hướng về ai?! Một bộ phim hài lãng mạn tươi vui và sống động khắc họa quá trình tìm kiếm bạn trai.",
    },
    {   
        id:"spirit-fingers",
        tieuDe: "Spirit Fingers",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Spirit-Fingers.jpg",
        phuDe: "Spirit Finger",

        thoiLuong:"100 phút",
        daoDien:"Lee Chul Ha",
        dienVien:"Park Ji Hu, Cho Jun Young, Choi Bo Min",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện kể về Song Woo Yeon là một nữ sinh trung học nhút nhát và sống khép kín, không rõ mục đích sống cũng như khó thể hiện cảm xúc. Cuộc đời cô thay đổi khi được mời làm người mẫu cho câu lạc bộ vẽ “Spirit Fingers”, nơi cô gặp những con người chân thành và cởi mở. Nhờ sự khích lệ của phó chủ tịch Nam Geu Rin, Woo Yeon gia nhập câu lạc bộ. Tại đây, cô gặp Nam Ki Jeong là em trai Geu Rin, một người mẫu có ngoại hình nổi bật nhưng bối rối về giá trị bản thân. Gặp Woo Yeon, Ki Jeong bắt đầu nuôi dưỡng những giấc mơ và cảm xúc mới mẻ về tình yêu. ",
    },
    {   
        id:"taxi-driver-season-3",
        tieuDe: "Taxi Driver Season 3",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Taxi-Driver-Season-3.jpg",
        phuDe: "Taxi Driver Season 3",

        thoiLuong:"100 phút",
        daoDien:"Unknown",
        dienVien:"Kim Hyeon Seo, Jung Myeong Cheol",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện kể về Song Woo Yeon là một nữ sinh trung học nhút nhát và sống khép kín, không rõ mục đích sống cũng như khó thể hiện cảm xúc. Cuộc đời cô thay đổi khi được mời làm người mẫu cho câu lạc bộ vẽ “Spirit Fingers”, nơi cô gặp những con người chân thành và cởi mở. Nhờ sự khích lệ của phó chủ tịch Nam Geu Rin, Woo Yeon gia nhập câu lạc bộ. Tại đây, cô gặp Nam Ki Jeong là em trai Geu Rin, một người mẫu có ngoại hình nổi bật nhưng bối rối về giá trị bản thân. Gặp Woo Yeon, Ki Jeong bắt đầu nuôi dưỡng những giấc mơ và cảm xúc mới mẻ về tình yêu.",
    },
    {   
        id:"mignon",
        tieuDe: "Mignon",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/MIGNON.jpg",
        phuDe: "Mignon",

        thoiLuong:"100 phút",
        daoDien:"Unknown",
        dienVien:"Oh Minhyeok, Kim Minju",
        khoiChieu:"01/01/2026",
        moTa:"Dưới ánh đèn thành phố rực rỡ là một đấu trường đẫm máu, tràn ngập tiếng la hét và gào thét điên cuồng. Những người đàn ông lực lưỡng tham gia các trận đấu quyền anh để kiếm tiền, trong khi khán giả của họ tuyệt vọng hy vọng rằng những người họ chọn sẽ mang lại vận may cho họ. Đối với ngôi sao trẻ đang lên Mignon, chỉ có một nơi duy nhất có thể thoát khỏi sự hỗn loạn của sàn đấu và cuộc sống khắc nghiệt của anh. Vị bác sĩ bí ẩn Oh Young-One, một võ sĩ ngầm, sẵn sàng phục vụ các võ sĩ bị thương, và Mignon với đôi mắt mở to, tìm thấy sự an ủi trong phòng khám yên tĩnh của mình. Young-One dịu dàng và chu đáo, luôn chăm sóc những vết thương của Mignon, chủ yếu đến từ thế giới tàn khốc bên ngoài sàn đấu. Tuy nhiên, vị bác sĩ này che giấu một bí mật cấm kỵ về bản thân. Trong một khoảnh khắc bất cẩn hiếm hoi, anh đã tiết lộ bí mật đó cho Mignon, khiến mạng sống của anh bị đe dọa. Mặc dù Young-One đã cảnh báo Mignon giữ khoảng cách để bảo vệ anh, Mignon vẫn cứng đầu và không chịu bỏ rơi người duy nhất khiến anh cảm thấy mình thực sự quan trọng.",
    },
    {   
        id:"would-you-marry-me",
        tieuDe: "Would You Marry Me",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Would-You-Marry-Me.jpg",
        phuDe: "Would You Marry Me",

        thoiLuong:"100 phút",
        daoDien:"UnSong Hyun Wook, Hwang In Hyeokknown",
        dienVien:"Choi Woo Shik, Jung So Min",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện về Kim U Ju là con trai duy nhất và là người thừa kế đời thứ tư của Myungsoondang, tiệm bánh lâu đời nhất Hàn Quốc, được thành lập cách đây 80 năm. Anh là một trưởng nhóm tiếp thị tài năng và cầu toàn, nhưng lại là một người tự luyến lý trí, quyết tâm điều hành công việc kinh doanh của gia đình thay cho người cha quá cố. Mối quan hệ công việc của anh với Yoo Me Ri, một nhà thiết kế từ một công ty đối tác, bất ngờ rẽ sang một hướng khác, đẩy họ vào một tình huống trớ trêu buộc anh phải trở thành chồng giả của cô. Yoo Me Ri là một nhà thiết kế lập dị và nóng tính, cô tìm kiếm một người chồng giả để bảo vệ giải thưởng đặc biệt của cặp đôi mới cưới là một căn nhà phố hạng sang. Cô là một cô dâu tương lai, sau khi trải qua hàng loạt khó khăn trong cuộc đời, bao gồm cả việc hôn ước bị hủy bỏ do sự không chung thủy của vị hôn phu và một hợp đồng thuê nhà gian lận, đã cầu hôn Kim U Ju, người trùng tên với vị hôn phu cũ của cô, để bảo vệ căn nhà mới cưới mà cô giành được sau khi chia tay. ",
    },
    {   
        id:"typhoon-family",
        tieuDe: "Typhoon Family",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Typhoon-Family.jpg",
        phuDe: "Typhoon Family",

        thoiLuong:"100 phút",
        daoDien:"Lee Na Jung",
        dienVien:"Lee Jun Ho, Kim Min Ha",
        khoiChieu:"01/01/2026",
        moTa:"Lấy bối cảnh năm 1997, khi nền kinh tế Hàn Quốc đang trải qua một cuộc khủng hoảng. Cha của Kang Tae Pung điều hành một công ty nhỏ tên là Typhoon Trading Company. Nhờ người cha giàu có, Kang Tae Pung sống một cuộc sống vô tư lự, nhưng cuộc khủng hoảng kinh tế tồi tệ nhất ập đến Hàn Quốc. Điều này đã thay đổi tất cả. Trong khi cuộc khủng hoảng kinh tế ập đến Typhoon Trading Company, cha của Kang Tae Pung qua đời. Kang Tae Pung quyết tâm không để công ty mà cha anh yêu thương như gia đình mình phá sản. Kang Tae Pung bước vào vị trí CEO và cứu công ty. Mặc dù còn non nớt trong quá khứ, anh sở hữu một trái tim ấm áp, tinh thần trách nhiệm mạnh mẽ và tinh thần dám thử thách. Anh cùng gia đình và các nhân viên, bao gồm cả O Mi Seon, phải vật lộn để cứu công ty. O Mi Seon là con gái cả trong gia đình và gánh vác gánh nặng gia đình trên vai. Cô làm kế toán tại Typhoon Trading Company. Cô làm những công việc như rửa chén, lau dọn, dán hóa đơn và sắp xếp sổ sách. Trong khi Kang Tae Pung cố gắng cứu công ty, O Mi Seon lại tìm thấy hy vọng từ sự xuất hiện của anh. Với sự cần cù và chân thành, cô mơ ước trở thành một nữ doanh nhân thành đạt tại Công ty Thương mại Typhoon.",
    },
    {   
        id:"than-den-oi-uoc-di",
        tieuDe: "Thần Đèn Ơi, Ước Đi",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/than-den-oi-uoc-di.jpg",
        phuDe: "Genie, Make A Wish",

        thoiLuong:"100 phút",
        daoDien:"Lee Byung Hun",
        dienVien:"Bae Suzy, Kim Woo Bin",
        khoiChieu:"01/01/2026",
        moTa:"Genie là một thần đèn quỷ quyệt, được giải phóng sau nghìn năm, sống bằng cách dụ dỗ con người qua những ham muốn sâu kín. Chủ nhân mới của anh là Ka Young, một phụ nữ lạnh lùng, không bị cảm xúc chi phối.Thay vì ước nguyện, cô thách thức thần đèn với một cuộc cá cược “năm trận đấu”: Nếu anh chứng minh được rằng con người luôn trở nên tha hóa, cô sẽ thực hiện tất cả các điều ước – và đánh đổi cả cuộc đời mình.",
    },
    {   
        id:"the-story-of-bihyung-enchanted-master-of-the-goblin",
        tieuDe: "The Story Of Bihyung: Enchanted Master Of The Goblin",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/The-Story-of-Bihyung-Enchanted-Master-of-the-Goblin.jpg",
        phuDe: "The Story Of Bihyung: Enchanted Master Of The Goblin",

        thoiLuong:"100 phút",
        daoDien:"Unknown",
        dienVien:"Hwang Jae Wook, Lee Cha Min   ",
        khoiChieu:"01/01/2026",
        moTa:"Ngày xửa ngày xưa, vào thời Silla, Yêu Tinh Bihyung đã ra đời, được muôn loài kính sợ. Tại Seoul thời hiện đại, chàng trai trẻ ngây thơ Geumbok, đang theo đuổi ước mơ trở thành diễn viên, đã trở thành nạn nhân của một vụ lừa đảo và trở thành người vô gia cư. Đúng lúc rắc rối chồng chất, Bihyung xuất hiện, dẫn đến một cuộc sống chung bất ngờ. Nhưng Geumbok lại ẩn chứa một sức mạnh bí ẩn và một mối liên kết định mệnh với Bihyung. Khi tình yêu và xung đột đan xen, liệu họ có thể phá vỡ lời nguyền ngàn năm?",
    },
    {   
        id:"my-secret-vampire",
        tieuDe: "My Secret Vampire",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/My-Secret-Vampire.jpg",
        phuDe: "My Secret Vampire",

        thoiLuong:"100 phút",
        daoDien:"Gi Mung",
        dienVien:"Yu Sin, Park Dong Ju, Lee Tae Hyeong",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện về Han Dong Ha là một chàng trai ngây thơ, sống ở vùng quê với người cha bệnh nặng. Sau khi cha mất, cậu thực hiện di nguyện của ông để lại - lên Seoul học đại học. Tại đây, Dong Ha tìm được một căn hộ chung giá rẻ bất ngờ, chỉ có một điều kiện: cậu phải hiến máu định kỳ cho chủ nhà. Ban đầu, Dong Ha thấy cuộc sống mới thật lý tưởng - tiền thuê rẻ, bạn cùng phòng tốt bụng, mọi sinh hoạt đều được chăm lo. Nhưng dần dần, cậu nhận ra những điều kỳ lạ: tại sao mọi người xung quanh lại quan tâm quá mức đến mùi hương và cơ thể cậu? Thực chất, những người bạn cùng phòng ấy đều là ma cà rồng. Họ bị thu hút bởi “mùi vị đặc biệt” trong máu của Dong Ha. Giữa những bí mật ngập tràn dối trá, Dong Ha rơi vào mối quan hệ vừa nguy hiểm vừa ngọt ngào, nơi ranh giới giữa tình yêu và sự sống còn trở nên mỏng manh.",
    },
    {   
        id:"ngu-tru-cua-bao-chua",
        tieuDe: "Ngự Trù Của Bạo Chúa",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/ngu-tru-cua-bao-chua.jpg",
        phuDe: "The Tyrant Chef",

        thoiLuong:"100 phút",
        daoDien:"Jang Tae Yoo",
        dienVien:"Lim Yoon A, Lee Chae Min",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện kể về một đầu bếp người Pháp bất ngờ vượt thời gian quay ngược 500 năm về quá khứ và gặp gỡ bạo chúa tàn ác nhất đồng thời cũng là một người sành ăn trong thời kỳ đó. Lim Yoona và Lee Chae Min sẽ đồng thời thủ vai chính cho bộ phim này.",
    },
    {   
        id:"my-bias-is-showing",
        tieuDe: "My Bias Is Showing",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/My-Bias-Is-Showing.jpg",
        phuDe: "My Bias Is Showing",

        thoiLuong:"100 phút",
        daoDien:"Baek Min Hee",
        dienVien:"Kim Kang Min, Kevin, Lee Byung Hun",
        khoiChieu:"01/01/2026",
        moTa:"Khi giáo viên trung học Na Ae Joon đến làm việc vào một ngày bình thường, anh không ngờ mình lại tình cờ gặp người nổi tiếng yêu thích ở hành lang. Nhưng khi trường học của anh trở thành địa điểm quay phim cho một chương trình có sự tham gia của Choi Si Yeol, thần tượng của anh trong nhóm nhạc thần tượng A-One, thì mọi chuyện đã xảy ra đúng như vậy! Nếu điều đó chưa đủ khiến một fanboy lên cơn đau tim, Si Yeol lại để ý đến Ae Joon và mời anh tham gia chương trình với tư cách là 'đồng nghiệp'. Vì muốn giữ bí mật về cuộc sống của mình với người hâm mộ, Ae Joon buộc phải thử thách khả năng diễn xuất, không chỉ trước ống kính. Nhưng khi anh dành nhiều thời gian hơn với Si Yeol, sự lừa dối này càng trở nên khó kiểm soát. Chưa kể, anh có thể không phải là người duy nhất giữ bí mật...",
    },
    {   
        id:"phim-head-over-heels",
        tieuDe: "Head Over Heels",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Head-over-Heels.jpg",
        phuDe: "Head Over Heels",

        thoiLuong:"100 phút",
        daoDien:"Kim Yong Wan",
        dienVien:"Cho Yi Hyun, Choo Young Woo, Cha Kang Yoon",
        khoiChieu:"01/01/2026",
        moTa:"Dựa trên một webtoon nổi tiếng, bộ phim là một câu chuyện tình lãng mạn kỳ ảo về một chàng trai định mệnh phải chết và một pháp sư trẻ cố gắng giải cứu anh ta khỏi số phận của mình. Cho Yi Hyun sẽ vào vai Park Sung Ah, là một học sinh trung học, nhưng vào ban đêm, cô lại là một pháp sư có tên là Tiên nữ Cheonji. Khi hành nghề pháp sư, cô thường che một phần khuôn mặt để giấu đi danh tính của mình. Cô nổi tiếng với danh xưng Tiên nữ Cheonji và rất bận rộn với những khách hàng đến để hỏi về tương lai, vận mệnh, bệnh tật và nhiều điều khác. Một đêm nọ, Bae Gyeon Woo (do Choo Yeong Woo thủ vai) cùng mẹ đến gặp Tiên nữ Cheonji. Park Sung Ah ngay lập tức cảm nắng anh, nhưng cô nhìn thấy rằng anh đang mang vận mệnh sẽ chết sớm. Ngày hôm sau, Bae Gyeon Woo xuất hiện trước mặt cô với tư cách là học sinh chuyển trường mới trong lớp cô. Cô quyết định sẽ cứu anh khỏi số phận nghiệt ngã đó.",
    },
    {   
        id:"law-and-the-city",
        tieuDe: "Law And The City",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Law-And-The-City.jpg",
        phuDe: "Law And The City",

        thoiLuong:"100 phút",
        daoDien:"Park Seung Woo",
        dienVien:"Lee Jong Suk, Mun Ka Young, Kang You Seok",
        khoiChieu:"01/01/2026",
        moTa:"Bộ phim mang đến sự kết hợp hứa hẹn rất thú vị giữa hai thể loại luật pháp và lãng mạn, xoay quanh những mảnh ghép đối lập của năm luật sư tại Johwa Law Firm, trong đó có An Ju Hyeong (do Lee Jong Suk thủ vai) – một cộng sự cấp cao lạnh lùng nhưng cực kỳ xuất sắc. Sự kết hợp giữa Moon Ga Young và Lee Jong Suk đang là điểm nhấn đáng chú ý của dự án, hứa hẹn mang đến những tương tác bùng nổ chemistry.",
    },
    {   
        id:"s-line",
        tieuDe: "Sợi Chỉ Tử Thần",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/S-Line.jpg",
        phuDe: "S Line",

        thoiLuong:"100 phút",
        daoDien:"Ahn Joo Young",
        dienVien:"Lee Da Hee, Lee Soo Hyuk, A Rin",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện xoay quanh câu chuyện bắt đầu khi xuất hiện một cặp kính có thể giúp người ta nhìn thấy những sợi chỉ màu đỏ bí ẩn, được gọi là 'S Line', xuất hiện trên đầu mỗi người và kết nối họ với từng cá nhân đã có quan hệ thexac. Từ đây, đời sống riêng tư đã bị đảo lộn, một cô gái tên Hyun Hob (Arin thủ vai) - người có khả năng nhìn thấy S Line từ khi mới sinh ra, cùng với Han Ji Wook (Lee Soo Hyuk thủ vai) - một thám tử, sẽ bắt tay để khám phá sự thật và giải quyết cuộc khủng hoảng này. ",
    },
    {   
        id:"muu-luoc-tinh-yeu-cua-chang-nhat-bong",
        tieuDe: "Mưu Lược Tình Yêu Của Chàng Nhặt Bóng",
        hinhAnh: "https://www.motchill20.net/wp-content/uploads/Muu-Luoc-Tinh-Yeu-Cua-Chang-Nhat-Bong.jpg",
        phuDe: "Ball Boy Tactics",

        thoiLuong:"100 phút",
        daoDien:"Kim Eun Hye",
        dienVien:"Choi Jae Hyeok, Yeom Min Hyeok",
        khoiChieu:"01/01/2026",
        moTa:"Sau khi giải nghệ khỏi bộ môn thể dục dụng cụ, Han Ji Won nghĩ rằng những thách thức lớn nhất của anh đã ở phía sau. Hóa ra, giành huy chương Olympic dễ hơn nhiều so với việc sống sót ở trường đại học với tư cách là một cựu siêu sao nhút nhát. Xuất hiện Kwon Jeong U là người đẹp trai trong trường, ngôi sao bóng rổ và cả một thế giới rắc rối mới được gói gọn trong nụ cười hoàn hảo. Nhưng ngay khi Ji Won nghĩ rằng anh đã hiểu Jeong U, anh lại phát hiện ra một khía cạnh ngọt ngào đáng ngạc nhiên ẩn sau vẻ ngoài lạnh lùng đó. Liệu cặp đôi không giống nhau này có thể vượt qua những khác biệt của họ và giữ vững mối tình lãng mạn đang chớm nở của họ không?",
    }
]

const danhSachXepHang = [
    {   
        id:"mignon",
        rank:1,
        tieuDe:"MIGNON",
        phuDe:"Mignon",
        diem:"7.8",
        nam:2023,
        hinhAnh:"https://www.motchill20.net/wp-content/uploads/MIGNON.jpg",

        thoiLuong:"100 phút",
        daoDien:"Unknown",
        dienVien:"Oh Minhyeok, Kim Minju",
        khoiChieu:"01/01/2026",
        moTa:"Dưới ánh đèn thành phố rực rỡ là một đấu trường đẫm máu, tràn ngập tiếng la hét và gào thét điên cuồng. Những người đàn ông lực lưỡng tham gia các trận đấu quyền anh để kiếm tiền, trong khi khán giả của họ tuyệt vọng hy vọng rằng những người họ chọn sẽ mang lại vận may cho họ. Đối với ngôi sao trẻ đang lên Mignon, chỉ có một nơi duy nhất có thể thoát khỏi sự hỗn loạn của sàn đấu và cuộc sống khắc nghiệt của anh. Vị bác sĩ bí ẩn Oh Young-One, một võ sĩ ngầm, sẵn sàng phục vụ các võ sĩ bị thương, và Mignon với đôi mắt mở to, tìm thấy sự an ủi trong phòng khám yên tĩnh của mình. Young-One dịu dàng và chu đáo, luôn chăm sóc những vết thương của Mignon, chủ yếu đến từ thế giới tàn khốc bên ngoài sàn đấu. Tuy nhiên, vị bác sĩ này che giấu một bí mật cấm kỵ về bản thân. Trong một khoảnh khắc bất cẩn hiếm hoi, anh đã tiết lộ bí mật đó cho Mignon, khiến mạng sống của anh bị đe dọa. Mặc dù Young-One đã cảnh báo Mignon giữ khoảng cách để bảo vệ anh, Mignon vẫn cứng đầu và không chịu bỏ rơi người duy nhất khiến anh cảm thấy mình thực sự quan trọng.",
    
    },
    {   
        id:"thuy-long-ngam",
        rank:2,
        tieuDe:"Thủy Long Ngâm",
        phuDe:"Whispers of Fate",
        diem:7.3,
        nam:2025,
        hinhAnh:"https://bloganchoi.com/wp-content/uploads/2023/11/poster-khai-niem-1-696x1237.jpg",
        thoiLuong:"100 phút",
        daoDien:"Trần Trụ Phí, Tiền Kính Ngọ",
        dienVien:"La Vân Hi, Tiêu Thuận Nghiêu",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện về Đường Lệ Tử là cao thủ xuất thân từ “Dị Cảnh”, mang tính cách nửa chính nửa tà. Sau vụ án diệt môn đầy bí ẩn, chàng bị cuốn vào vòng xoáy tranh chấp quyền lực giữa các thế lực võ lâm. Khi điều tra chân tướng, Đường Lệ Tử phát hiện kẻ đứng sau mọi âm mưu lại chính là Liễu Nhẫn – sư huynh năm xưa. Liễu Nhẫn âm mưu thành lập Khóa Sinh Điện, sử dụng độc dược đặc chế nhằm khống chế toàn bộ võ lâm và thống trị thiên hạ. Nhận ra hiểm họa đang lan rộng, Đường Lệ Tử buộc phải hợp sức với các môn phái chính đạo để ngăn chặn kế hoạch tàn độc này. Trên hành trình ấy, chàng đối mặt với những ân oán cũ, những bí mật bị chôn giấu và sự thật về loại độc năm xưa. Cuối cùng, từ một kẻ cô độc chỉ sống cho bản thân, Đường Lệ Tử dần nhận ra sứ mệnh lớn lao của mình: gánh vác trách nhiệm bảo vệ giang hồ khỏi diệt vong. ",
    },
    {   
        id:"the-manipulated",
        rank:3,
        tieuDe:"The Manipulated",
        phuDe:"The Manipulated",
        diem:"9.8",
        nam:2025,
        hinhAnh:"https://www.motchill20.net/wp-content/uploads/The-Manipulated.jpg",

        thoiLuong:"100 phút",
        daoDien:"Park Shin Woo, Kim Chang Ju",
        dienVien:"Ji Chang Wook, Doh Kyung Soo",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện xoay quanh Tae Jung do Ji Chang Wook thủ vai một người đàn ông bình thường bị buộc tội oan trong vụ án giết người được dàn dựng một cách tỉ mỉ và phải vào tù. Sau khi phát hiện ra mọi chuyện đều do Yohan do Do Kyung Soo thủ vai dàn dựng, anh quyết tâm trả thù.",
    },
    {   
        id:"dear-x",
        rank:4,
        tieuDe:"Dear X",
        phuDe:"Dear X",
        diem:"8",
        nam:2025,
        hinhAnh:"https://www.motchill20.net/wp-content/uploads/Dear-X.jpg",

        thoiLuong:"100 phút",
        daoDien:"Lee Eung Bok, Park So Hyun",
        dienVien:"Kim You Jung, Kim Young Dae, Kim Do Hoon",
        khoiChieu:"01/01/2026",
        moTa:"Baek A Jin lớn lên trong cảnh bạo lực gia đình, buộc cô phải che giấu cảm xúc và sống sót bằng cách đọc vị và thao túng người khác. Bề ngoài, cô tỏ ra hào phóng và tốt bụng, nhưng khi tham vọng bị đe dọa, bản chất đen tối trong cô lại trỗi dậy. Với nhan sắc và tài năng, cô vươn lên trở thành một nữ diễn viên hàng đầu. Bên cạnh cô là Yun Jun Seo, người bạn tâm giao suốt đời và là người duy nhất cô tin tưởng. Vậy mà người đàn ông từng ủng hộ cô lại chính là người khiến cô sụp đổ. Cũng liên quan đến quá khứ của cô là Kim Jae O, người có quá khứ bị bạo hành và tìm thấy ở A Jin lý do để sống. Trong khi đó, nữ diễn viên đối thủ và cựu thần tượng Im Re Na lại nảy sinh tình cảm với Jun Seo, khiến cuộc sống của họ thêm phần căng thẳng. ",
    },
    {   
        id:"song-trung",
        rank:5,
        tieuDe:"Song Trùng",
        phuDe:"Decalcomania",
        diem:"5.7",
        nam:2025,
        hinhAnh:"https://www.motchill20.net/wp-content/uploads/song-trung.jpg",

        thoiLuong:"100 phút",
        daoDien:"Wo Worawit Khuttiyayothin",
        dienVien:"Mookda Narinrak, Hussawee Pakrapongpisan",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện kể về hai người phụ nữ trông hoàn toàn giống nhau nhưng lại sống những cuộc đời hoàn toàn khác biệt. Chuyện gì sẽ xảy ra khi họ thức dậy trong thân xác của nhau? Nuengdiao Ananthikhun, chủ một hộp đêm ở Bangkok với quá khứ đen tối, và Lea Wu, một phụ nữ Singapore giàu có sống dưới sự bảo vệ của một ông trùm dược phẩm, đã gặp phải một tai nạn bí ẩn. Trong lúc hỗn loạn, linh hồn họ hoán đổi cho nhau, và chẳng bao lâu sau, những bí mật mà họ đã chôn giấu suốt đời dần dần được hé lộ. Một người phải sinh tồn trong thế giới thượng lưu đầy rẫy những mánh khóe. Người kia phải đương đầu với một thế giới ngầm nguy hiểm mà cô chưa từng biết đến. Không ai chuẩn bị cho những gì họ sẽ gặp phải. ",
    },
    {   
        id:"me-and-three",
        rank:6,
        tieuDe:"Me And Thee",
        phuDe:"Me And Thee",
        diem:"9.6",
        nam:2025,
        hinhAnh:"https://www.motchill20.net/wp-content/uploads/Me-and-Thee-The-Series.jpg",

        thoiLuong:"100 phút",
        daoDien:"X Nuttapong Mongkolsawas",
        dienVien:"Naravit Lertratkosum, Phuwin Tangsakyuen",
        khoiChieu:"01/01/2026",
        moTa:"Sau cuộc gặp gỡ đầu tiên đầy kịch tính, nhiếp ảnh gia Peach trở thành huấn luyện viên cuộc sống nghiệp dư cho doanh nhân giàu có Thee. Mải mê phim truyền hình và không còn biết đến giá trị của đồng baht, Khun Thee cần phải nhìn nhận lại thực tế. ",
    },
    {   
        id:"ban-than-tham-doc",
        rank:7,
        tieuDe:"Bạn Thân Thâm Độc",
        phuDe:"Friendshit Forever",
        diem:"9.7",
        nam:2025,
        hinhAnh:"https://www.motchill20.net/wp-content/uploads/Friendshit-Forever.jpg",

        thoiLuong:"100 phút",
        daoDien:"Koo Ekkasit Trakulkasemsuk",
        dienVien:"Chayanit Chansangavej, Thasorn Klinnium",
        khoiChieu:"01/01/2026",
        moTa:"Câu chuyện về Tulip và Baikhao được cho là đôi bạn thân thiết. Tình bạn của họ trông đẹp đẽ khi nhìn từ xa, nhưng khi nhìn gần, nó lại chất chứa đầy sự đố kỵ và những mối hận thù dai dẳng không thể buông tha. Baikhao kết bạn với Tulip với ý định trả thù những gì cha Tulip đã làm với cô. Cô sẽ không dừng lại cho đến khi công lý được thực thi cho người cha đã tự sát và người mẹ phát điên sau khi mất em gái trong một lần sảy thai. Tulip sẽ bị lợi dụng như một công cụ để phá hoại chính gia đình mình. Baikhao nhận được sự giúp đỡ từ Tao, một người bạn thời trung học, người đã phải lòng cô suốt những năm qua và sẵn sàng làm bất cứ điều gì vì cô, thậm chí là giết người. Tullip có Namo, một người bạn cùng lớp mà cô lầm tưởng là gay nhưng thực ra lại yêu cô. Anh ta có thể không xứng với cô về mặt địa vị xã hội, nhưng bất kể chuyện gì xảy ra với Tulip, Namo đều sẵn sàng đánh cược mạng sống của mình, và anh phải cứu Tulip khỏi âm mưu đen tối của Baikhao.",
    },
]